### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by LiguoJin1206** [kulia/Hilbert-Huang_transform#2]
In line 34 of the emd.m function,  "numberOfImf = numberOfImf(signalLength);" ,  the function numberOfImf is not defined.

**Comment by NouveauCN** [comment]
hi, just rename the variable or function name. Matlab could not tell between variable and function with the same name.
BTW, when calling 'linearSplineNearBoundery.m' , the author typed 'linearSplineNearBoundary' sometimes. (e->a)
